
# vim ft=yaml
# CI on Windows via appveyor
# Largely from:
# https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
#
# Builds version specified in BUILD_COMMIT variable
# To chose version to build, edit value of BUILD_COMMIT

os: Visual Studio 2015

environment:
    global:
      MINGW_32: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
      MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
      BUILD_COMMIT: v0.10.0

    matrix:
    # - PYTHON: C:\Python39
    #   PYTHON_VERSION: 3.9
    #   PYTHON_ARCH: 32

    # - PYTHON: C:\Python39-x64
    #   PYTHON_VERSION: 3.9
    #   PYTHON_ARCH: 64

    # - PYTHON: C:\Python38
    #   PYTHON_VERSION: 3.8
    #   PYTHON_ARCH: 32

    # - PYTHON: C:\Python38-x64
    #   PYTHON_VERSION: 3.8
    #   PYTHON_ARCH: 64

    # - PYTHON: C:\Python37
    #   PYTHON_VERSION: 3.7
    #   PYTHON_ARCH: 32

    # - PYTHON: C:\Python37-x64
    #   PYTHON_VERSION: 3.7
    #   PYTHON_ARCH: 64

    # - PYTHON: C:\Python36
    #   PYTHON_VERSION: 3.6
    #   PYTHON_ARCH: 32

    - PYTHON: C:\Python36-x64
      PYTHON_ARCH: 64
install:
  - cmd: echo "Using cmd"

  # Get needed submodules
  - git submodule update --init

  # Install new Python if necessary
  - ps: .\multibuild\install_python.ps1

  - ps: |
      $PYTHON_ARCH = $env:PYTHON_ARCH
      If ($PYTHON_ARCH -eq 32) {
          $MINGW = $env:MINGW_32
      } Else {
          $MINGW = $env:MINGW_64
      }
      $env:Path += ";$MINGW"
      $env:NPY_NUM_BUILD_JOBS = "4"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

  # Fix MSVC builds for 64-bit Python
  # See
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version

  - python -m pip install --upgrade pip setuptools
  - pip install wheel

build_script:
  # Build and install the wheel
  - cd sisl
  - git fetch origin
  - git checkout %BUILD_COMMIT%
  - pip install -r requirements.txt
  - pip install Cython

  - python setup.py bdist_wheel
  - ps: |
      # Upload artifact to Appveyor immediately after build
      ls dist -r | Foreach-Object {
          appveyor PushArtifact $_.FullName
      }
  - pip install --pre --no-index -f .\dist sisl

test_script:
  # Run some tests
  - set CFLAGS="/Od"

after_test:
  # If tests are successful, create binary packages for the project.
  - dir dist

deploy:
  release: $(BUILD_COMMIT)
  description: 'Wheels for sisl-$(BUILD_COMMIT)'
  provider: GitHub
  auth_token:
    secure: 0QIgDvK+vuiC36uPQ1NLiOMujWRuOLPe5x2tJ4doi7fSR7W9OUsfqlHWTAuK6XOz
  draft: false
  prerelease: false
  force_update: true
  #on:
    #branch: release                 # release from this branch only
    #APPVEYOR_REPO_TAG: true          # deploy on tag push only